### ISSUE TITLE
Doesn't install on Windows

### ISSUE THREAD

**Issue by fristys** [CryogenicPlanet/depp#1]
I get the following error when I run `npm i -g depp-installer` on Windows 10:

```
> depp-installer@0.0.1-e preuninstall C:\Program Files\nodejs\node_modules\depp-installer
> node dist/postinstall.js uninstall

Uninstalled cli successfully

> depp-installer@0.0.1-e postinstall C:\Program Files\nodejs\node_modules\depp-installer
> node dist/postinstall.js install

Copying the relevant binary for your platform win32
Downloading binary from https://github.com/CryogenicPlanet/depp/releases/download/v0.0.1-e/depp.exe_0.0.1-e_windows_x86_64.tar.gz
(node:7564) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (C:\Users\mgg\AppData\Roaming\nvm\v14.15.0\node_modules\depp-installer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\mgg\AppData\Roaming\nvm\v14.15.0\node_modules\depp-installer\node_modules\axios\lib\core\settle.js:17:12)
    at RedirectableRequest.handleResponse (C:\Users\mgg\AppData\Roaming\nvm\v14.15.0\node_modules\depp-installer\node_modules\axios\lib\adapters\http.js:262:9)
    at RedirectableRequest.emit (events.js:315:20)
    at RedirectableRequest._processResponse (C:\Users\mgg\AppData\Roaming\nvm\v14.15.0\node_modules\depp-installer\node_modules\follow-redirects\index.js:425:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\Users\mgg\AppData\Roaming\nvm\v14.15.0\node_modules\depp-installer\node_modules\follow-redirects\index.js:57:10)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ depp-installer@0.0.1-e
updated 1 package in 4.43s
```

**Comment by CryogenicPlanet** [comment]
Hey sorry don't have a windows machine myself so had to reply on CI to make sure it works, but it seems to be finally working properly on Winodws (https://github.com/CryogenicPlanet/depp/runs/4093204800?check_suite_focus=true) . Lmk if you run into any troubles
